version: 2
endpoint: http://localhost:6060
metadata_directory: hasura/metadata
migrations_directory: hasura/migrations
seeds_directory: hasura/seeds
actions:
  kind: synchronous
  handler_webhook_baseurl: https://us-central1-letryx-web.cloudfunctions.net
