apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "web.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # TODO: add health-check endpoint(s) so we can add probes
          env:
            - name: AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.fullname" . }}
                  key: auth0-secret
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.fullname" . }}
                  key: auth0-client-id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.fullname" . }}
                  key: auth0-client-secret
            - name: DISCORD_SIGNUPS_HOOK
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.fullname" . }}
                  key: discord-signups-webhook
            - name: IP_STACK_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.fullname" . }}
                  key: ipstack-key
            {{- with .Values.config }}
            - name: AUTH0_SCOPE
              value: {{ required "Auth0 scope is required!" .auth0Scope | quote }}
            - name: AUTH0_BASE_URL
              value: {{ required "Auth0 base URL is required!" .auth0BaseURL | quote }}
            - name: AUTH0_AUDIENCE
              value: {{ required "Auth0 audience is required!" .auth0Audience | quote }}
            - name: AUTH0_ISSUER_BASE_URL
              value: {{ required "Auth0 issuer base URL is required!" .auth0IssuerBaseURL | quote }}
            - name: AUTH0_POST_LOGOUT_REDIRECT
              value: {{ required "Auth0 post logout redirect is required!" .auth0PostLogoutRedirect | quote }}
            - name: AUTH0_SESSION_ROLLING_DURATION
              value: {{ required "Auth0 session rolling duration is required!" .auth0SessionRollingDuration | quote }}
            - name: GRAPHQL_API_URL
              value: {{ required "GraphQL API URL is required!" .graphqlAPIURL | quote }}
            - name: GRAPHQL_API_SSR_URL
              value: {{ required "GraphQL API SSL URL is required!" .graphqlAPISSRURL | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
