apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
type: Opaque
data:
  {{- with .Values.config }}
  auth0-secret: {{ required "Auth0 secret is required!" .auth0Secret | b64enc | quote }}
  auth0-client-id: {{ required "Auth0 client ID is required!" .auth0ClientID | b64enc | quote }}
  auth0-client-secret: {{ required "Auth0 client secret is required!" .auth0ClientSecret | b64enc | quote }}
  discord-signups-webhook: {{ required "Discord signups webhoook is required!" .discordSignupsWebhook | b64enc | quote }}
  ipstack-key: {{ required "IPStack key is required!" .ipstackKey | b64enc | quote }}
  {{- end }}
