SET check_function_bodies = false;
INSERT INTO public.sec_contract_type (id, name) VALUES (1, 'purchase and sale agreement');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (2, 'energy assets', 1);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (3, 'gas purchase contract', 2);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (4, 'crude oil supply agreement', 2);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (5, 'gas supply agreement', 2);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (6, 'oil purchase and deliver agreement', 2);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (7, 'mixed assets', 1);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (8, 'membership interest purchase agreement', 7);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (9, 'stock purchase agreement', 7);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (10, 'unit purchase agreement', 7);
INSERT INTO public.sec_contract_type (id, name) VALUES (11, 'project agreements');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (12, 'facilities agreement', 11);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (13, 'undefined', 11);
INSERT INTO public.sec_contract_type (id, name) VALUES (14, 'operating agreements');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (15, 'omnibus operating agreement', 14);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (16, 'international operating agreement', 14);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (17, 'joint operating agreement', 14);
INSERT INTO public.sec_contract_type (id, name) VALUES (18, 'joint venture agreement');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (19, 'partnership agreement', 18);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (20, 'area of mutual interest agreement', 18);
INSERT INTO public.sec_contract_type (id, name) VALUES (21, 'royalty agreement');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (22, 'production payment royalty agreement', 21);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (23, 'conveyance of net profits interest', 21);
INSERT INTO public.sec_contract_type (id, name) VALUES (24, 'participation and farmout agreements');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (25, 'participation agreement', 24);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (26, 'farm-out agreement', 24);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (27, 'asset exploration agreement', 24);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (28, 'production participation plan payment agreement', 24);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (29, 'exploration agreement', 24);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (30, 'drilling participation agreement', 24);
INSERT INTO public.sec_contract_type (id, name) VALUES (31, 'lease agreement');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (32, 'petroleum and natural gas lease', 31);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (33, 'equipment lease agreement', 31);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (34, 'mineral lease', 31);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (35, 'oil sands lease', 31);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (36, 'production system lease agreement', 31);
INSERT INTO public.sec_contract_type (id, name) VALUES (37, 'power purchase agreement');
INSERT INTO public.sec_contract_type (id, name) VALUES (38, 'swap agreements');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (39, 'crude oil swap agreement', 38);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (40, 'natural gas swap agreement', 38);
INSERT INTO public.sec_contract_type (id, name) VALUES (41, 'assignment agreements and deeds');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (42, 'NEW_assignment_of_royalty_interest', 41);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (43, 'assignment of overriding royalty interest', 42);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (44, 'assignment agreement', 41);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (45, 'assignment and transfer agreement', 41);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (46, 'assignment, conveyance and bill of sale', 41);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (47, 'deed of guaranty and indemnity', 41);
INSERT INTO public.sec_contract_type (id, name) VALUES (48, 'service contracts');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (49, 'service agreement', 48);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (50, 'contract operating agreement', 48);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (51, 'personnel services agreement', 48);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (52, 'administrative services agreement', 48);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (53, 'consulting services agreement', 48);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (54, 'management agreement', 48);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (55, 'support agreement', 48);
INSERT INTO public.sec_contract_type (id, name) VALUES (56, 'midstream contracts');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (57, 'gathering agreements', 56);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (58, 'gas gathering agreement', 57);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (59, 'throughput agreement', 56);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (60, 'separation agreement', 56);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (61, 'natural gas treating & condensate handling agreement', 56);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (62, 'conveyance of gas processing rights', 56);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (63, 'gas transportation and sales agreement', 56);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (64, 'pipeline construction and operating agreement', 56);
INSERT INTO public.sec_contract_type (id, name) VALUES (65, 'IP agreements');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (66, 'license agreement', 65);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (67, 'subsurface mineral resources license', 66);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (68, 'technology license agreement', 65);
INSERT INTO public.sec_contract_type (id, name) VALUES (69, 'contribution agreement');
INSERT INTO public.sec_contract_type (id, name) VALUES (70, 'undefined');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (71, 'credit agreement', 70);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (72, 'deed of trust', 70);
INSERT INTO public.sec_contract_type (id, name) VALUES (73, 'tax agreements');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (74, 'tax sharing agreement', 73);
INSERT INTO public.sec_contract_type (id, name) VALUES (75, 'option agreement');
INSERT INTO public.sec_contract_type (id, name) VALUES (76, 'hard mineral agreements');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (77, 'coal purchase contract', 76);
INSERT INTO public.sec_contract_type (id, name) VALUES (78, 'misc');
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (79, 'bill of sale', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (80, 'shipyard contract', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (81, 'production sharing contract', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (82, 'master offset agreement', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (83, 'employment agreement', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (84, 'non-competition agreement', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (85, 'indemnification agreement', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (86, 'change of control agreementnotes/debt', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (87, 'drilling purchase agreement', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (88, 'merger agreement', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (89, 'option and joint venture agreement', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (90, 'press release', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (91, 'production and marketing agreement', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (92, 'shareholder agreement', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (93, 'turnkey drilling contract', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (94, 'securities', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (95, 'contribution, conveyance and assumption agreement', 78);
INSERT INTO public.sec_contract_type (id, name, parent_id) VALUES (96, 'mortgage, assignment of production', 78);