apiVersion: v2
name: web
version: 0.1.0
description: Letryx frontend web application
type: application
home: https://github.com/letryx/web/tree/master/charts/web
sources:
  - https://github.com/letryx/web
dependencies:
  - name: common
    version: 1.10.0
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: letryx
    email: dev@letryx.com
appVersion: "main"
