name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GRAPHQL_API_URL: https://api.letryx.com/v1/graphql
      GRAPHQL_API_SSR_URL: https://api.letryx.com/v1/graphql
      # use random secret to prevent `TypeError: "secret" is required`
      AUTH0_SECRET: Y1cgGEHhbYXt0ZZAblvC46NtW7aJhkqW
      AUTH0_ISSUER_BASE_URL: https://letryx.us.auth0.com
      AUTH0_BASE_URL: http://localhost:3000
      AUTH0_CLIENT_ID: j2Zg8RLw6htnoB8I7hlKYxa8JVmDFUGR
      AUTH0_CLIENT_SECRET: 2bAxof3JccJmKQIRIa7AwdpFk93qERx8_gjttfdzaUJLPfqWIOMxOyivToKOd-yZ
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install Deps
        run: yarn install
      - name: Typecheck
        run: yarn type-check
      - name: Lint js
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
